### ISSUE TITLE
bug: cloning the repo with --recurse-submodules fails with ERROR

### ISSUE THREAD

**Issue by markdoerr** [biosustain/lifelike#1]
Hej lifelike team,

I was trying to clone the repo for testing:

git clone --recurse-submodules https://github.com/biosustain/lifelike.git

But it failed with:

Cloning into '/my_source_dir/semantics_ontologies/lifelike/deployment'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:SBRG/lifelike-infra.git' into submodule path '/lair/source/collection/semantics_ontologies/lifelike/deployment' failed
Failed to clone 'deployment' a second time, aborting

Do you know the cause of this error ? Tak :) mark

**Comment by Skitionek** [comment]
We are having bit of problem on how we structured our repository, particularly deployment code is added as submodule of main repository. While lifelike is (trying to be) opensource we decided to not share our deployment scripts - they are truly our case / cloud provider specific.

I will note it as a task and look into it whenever I will have some extra time on hand.

**Comment by Skitionek** [comment]
I have updated the code and project structure. With new version you should be about to run simply `make docker-run` to start development version. Please let me know if you have some more issues.

**Comment by markdoerr** [comment]
Thanks a lot @Skitionek,
and sorry for the late reply - I will test it right away :)

**Comment by markdoerr** [comment]
A short update on my next trial, @Skitionek,

while runnig the `make docker-run` command I received the following error:

```
docker compose exec appserver flask load-lmdb
Traceback (most recent call last):
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/n4j/app.py", line 459, in load_lmdb
    manager = LMDBManager(AzureStorageProvider(), 'lmdb')
  File "/home/n4j/neo4japp/lmdb_manager/manager.py", line 90, in __init__
    self.client = FileService(account_name=account_name, account_key=account_key)
  File "/usr/local/lib/python3.9/site-packages/azure/storage/file/fileservice.py", line 169, in __init__
    service_params = _ServiceParameters.get_service_parameters(
  File "/usr/local/lib/python3.9/site-packages/azure/storage/common/_connection.py", line 126, in get_service_parameters
    raise ValueError(_ERROR_STORAGE_MISSING_INFO)
ValueError: You need to provide an account name and either an account_key or sas_token when creating a storage service.
make: *** [makefile:7: lmdb] Error 1
```

maybe you have a quick fix (I have only limited time available, so I cannot fix myself). Thanks Dominik :)
